### ISSUE TITLE
Passing all arguments after repository name to git when cloning

### ISSUE THREAD

**Issue by cartoonist** [amir-s/dev#32]
For example, running `dev clone amir-s/dev --recursive [...]` should pass all arguments `--recursive [...]` to `git clone`.

**Comment by amir-s** [comment]
We currently have a few arguments that can be passed to the internal `git clone` command if the right configurations are set.

https://github.com/amir-s/dev/blob/33a856f438ce17d9737b6a08071da1583d4934d8/clone/index.mjs#L143-L154

This is not scalable and does not cover all the cases. Your idea is far better than what we have! We should just relay all the switches to the internal clone command. Do you see anything that can go wrong?

We can remove the existing configurations for `dev clone`.

**Comment by cartoonist** [comment]
I cannot think of any scenario that it goes wrong except that it might be confusing which options are picked up by `dev clone` and which ones will be relayed. For instance, we can unambiguously distinguish these two kinds of options by using `--` POSIX delimiter. That is all options and args after "--" will be considered as a single string and will be relayed to the underlying command.

This might be sufficient for `dev clone` but might not be such for other commands. Let's deal with it whenever anything fails 😄 or change it to be consistent throughout dev commands.

**Comment by amir-s** [comment]
I like using `--` but that should be the default for almost all `dev` commands. `dev clone` itself can by default pass all arguments to the underlying `git clone` without the need for `--`. We can address `--` separately.
