### ISSUE TITLE
Filtering project lists

### ISSUE THREAD

**Issue by cartoonist** [amir-s/dev#33]
`dev ps` lists all cloned repositories. It would be super useful if it offers some filtering mechanism. For example:

```shell
$ dev ps user:amir-s
# ...
# list of repositories by amir-s
# ...
$ dev ps org:github.com
# ...
# list of repositories hosted on github.com
# ...
```

**Comment by cartoonist** [comment]
No, `--user` is more consistent with the overall syntax especially since user and org are dev concepts rather than git or external commands. We can extend this by -f/--filter for more complex filters later.

**Comment by cartoonist** [comment]
I should note that the user might have repositories across multiple organisations.

**Comment by amir-s** [comment]
@cartoonist do you think multiple filters should be combined with `OR` or `AND`?

**Comment by cartoonist** [comment]
I would go for `AND` as if each arguement whether it is property-specific (like `--user`) or generic `--filter` further restricts the result of previous filters. For supporting other scenarios, `--filter` could accept regex like "foo|bar" for example. I don't know how to implement filtering "properties" which are not part of repo paths; for example filtering by organisation when organisation is not part of the clone path template. I am not sure having tags like `org:` or `user:` is easy to implement.
